### PR TITLE
changing json without root message from info to warn

### PR DESCRIPTION
**Pull request by nykolaslima**
IMO there is no reason to this log to be INFO instead of WARN. It's a common use to use JSON without root and it get's the log fully of unused messages.

What do you guys think about it? @Turini @lucascs @garcia-jj

### CODE REVIEW

**Comment by linyatis** [comment]
Hey all! I think that INFO is the best place for that, because the responsibility of each type of log.
WARN is for harmful situations (ass we can see [here](http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Level.html)).  
What do you think?

**Comment by nykolaslima** [comment]
Maybe DEBUG? IMO this information isn't useful to be logged as INFO.

**Comment by linyatis** [comment]
@nykolaslima, IMHO it makes sense to be logged as DEBUG.

**Comment by Turini** [comment]
Yes @nykolaslima, I agree that this is not the case to use an INFO.
I guess that @linyatis suggestion makes sense, using DEBUG instead
lets wait for more reviews, if no one downvote this, we can :sheep: this change

**Comment by lucascs** [comment]
:+1:

**Comment by Turini** [comment]
Thanks @nykolaslima! It'll be released soon

**Pull request merged**
