### PR TITLE
Fix warning 'No grammar constraints referenced in the document' in Ec…

### PR DESCRIPTION
**Pull request by fabriciofx**
…lipse IDE.

### CODE REVIEW

**Comment by Turini** [comment]
@fabriciofx which eclipse version are you using? I'm not with this warning here, using 
luna 4.2.2 (same using latest intellij idea). Besides that, I'm not sure if we should apply 
this change, since it's just like was specified on [bean validation spec](http://beanvalidation.org/1.0/spec/#xml-config). What do u think?

**Comment by fabriciofx** [comment]
@Turini I'm using Eclipse Luna 4.4.2 + JDK 1.8.0 u45 +  Windows 7 64 bits. Besides that, it's just a warning... not a bug. Do you think is a good idea we ask to caelum-vraptor mail list and ask if anyone has had the same warning?

**Comment by Turini** [comment]
Either the way, I think we should keep just like was specified on bean validation jsr.
It's just a warning and doen't happen in all environments/IDE. But sure, feel free to
send an email on vraptor mail list getting more feedbacks about it :) thanks fabricio

**Comment by Turini** [comment]
@fabriciofx I'm closing here, ok? If someone answer your thread on vraptor's mail
list or someone else ask for this change, we can reopen the PR. Thank you again.

**Pull request closed without merging**
