### PR TITLE
Adding search to VRaptor's site

### PR DESCRIPTION
**Pull request by luiz**
This solution is inspired on compass-style.org, which also uses nanoc for site generation (credits given on source where appropriated). It uses nanoc to generate a JS object with information from all pages. Then there's a JS file that processes what the user types and filters the object created by nanoc, rendering the filtered results on the page.

### CODE REVIEW

**Comment by luiz** [comment]
Oops, my fault. Didn't test it after running `grunt`. I'll check what is wrong with it and update my pull request ASAP.

PS: sorry for the delay

**Comment by luiz** [comment]
Ok, now it should work. I hadn't see that JS minification was done manually on Grunt to avoid minifying every copy of JS files that nanoc creates.

**Comment by Turini** [comment]
it's working like a charm now :) thanks @luiz!

**Comment by Turini** [comment]
vraptor-site deployed! Thanks a lot for doing it :+1:

**Pull request merged**
