### PR TITLE
Consistently handle superclass/subclass converters independent of class load order.

### PR DESCRIPTION
**Pull request by smbell**
See [issue 1059](https://github.com/caelum/vraptor4/issues/1059)

### CODE REVIEW

**Comment by Turini** [comment]
hey @smbell, 
I'll try and review this code soon to provide you a feedback, ok?
this all sounds great, btw. thx

**Comment by Turini** [comment]
sounds to work like a charm. I'll try in a large app soon, merging by now. Thx again

**Comment by smbell** [comment]
Great! My first actual open source contribution. :)

**Comment by Turini** [comment]
Wow, it's an honor to us! 
Welcome on board, @smbell. I'm looking forward for your next pull-request

**Pull request merged**
