### PR TITLE
fix resource leak in InputStreamDownload.java (input stream is never …

### PR DESCRIPTION
**Pull request by siddjain**
…closed)

### CODE REVIEW

**Comment by Turini** [comment]
thanks @siddjain! this sounds ok to me
may you think in a way to ensure this behaviour in a test case?

**Comment by siddjain** [comment]
Unfortunately I don't think I have time to write a test case at least for now. Perhaps create a work item for the test case?

Date: Mon, 23 May 2016 06:38:31 -0700

**Comment by angeliski** [comment]
Hey @siddjain, Can I help you writing a test case? I like to aprove that pull request. :)

**Comment by siddjain** [comment]
Sure


________________________________

**Comment by angeliski** [comment]
@siddjain I will open a new PR with the test case and that modification. Ok?

**Comment by siddjain** [comment]
Ok

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Dec 7, 2016 at 12:59 AM -0800, "Rogerio Angeliski" <notifications@github.com<mailto:notifications@github.com>> wrote:


@siddjain<https://github.com/siddjain> I will open a new PR with the test case and that modification. Ok?

**Comment by angeliski** [comment]
@siddjain Can I close that issue?

**Comment by siddjain** [comment]
Sure thanks

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Dec 8, 2016 at 6:23 AM -0800, "Rogerio Angeliski" <notifications@github.com<mailto:notifications@github.com>> wrote:


@siddjain<https://github.com/siddjain> Can I close that issue?

**Pull request closed without merging**
