### PR TITLE
letting web server commit the response naturally

### PR DESCRIPTION
**Pull request by nykolaslima**
@Turini @csokol this is related to https://github.com/caelum/vraptor4/issues/1035

### CODE REVIEW

**Comment by csokol** [comment]
Great, @nykolaslima!

But I think your PR broke the unit tests :disappointed: 

I guess you will probably need to flush the PrintWriter used on the tests manually.

**Comment by nykolaslima** [comment]
Yeah! I'm fixing it :cry:

**Comment by nykolaslima** [comment]
@csokol done!
thanks for the tip on custom `PrintWriter` :+1:

**Comment by Turini** [comment]
thanks @nykolaslima, this PR seems ok to me! 

@csokol @lucascs can you guys see any downside by doing this?
if not, i guess we can :rocket: here

**Comment by csokol** [comment]
I think that removing the early flush should not cause any problems, @Turini. If @lucascs is ok with it, then :ship: it.

**Comment by lucascs** [comment]
Imagine that:

I wrote "ok!" to the response. Didn't flush.

Transaction interceptor changes the status code to 500. Flushes.

We'll get a 500 error with ok! on the response.

We're fixing one bug and creating another one.

Maybe a better way to do this is to delay the response actions until after the interceptors run. 
So result.use(bla) would simply collect the actions and they would be run after the interceptor stack finishes...

this is a much bigger change, worthy of a major bump in VRaptor version, but we probably should do this eventually

**Comment by nykolaslima** [comment]
I agree with you @lucascs. But the problem that you related already exists.
For example, in your controller you wrote "ok". 
Some error occur after that, let's say the `HibernateTransactionInterceptor` failed to commit the transaction.
You have another interceptor that catches unexpected exception and wrote "failed because of exception {}".
When the response is flushed, it will containt "okfailed because of exception {}".

I was talking with @csokol to do exactly what you suggested, delay the write to after the interceptors run. But it will required a huge change in the framework.

I think that we are not creating another bug with this PR but we are not solving all bugs (response status and body). What do you think about merging this PR, that solves the response status problem and open a new issue to handle the "delayed response write"?

(ps: to workaround the problem with the messages wrote to the response, the interceptor could inject `HttpServletResponse` and call `reset` method http://docs.oracle.com/javaee/6/api/javax/servlet/ServletResponse.html#reset%28%29)

**Comment by lucascs** [comment]
:+1:

**Comment by nykolaslima** [comment]
Awesome @lucascs. I already opened an issue https://github.com/caelum/vraptor4/issues/1037

**Comment by nykolaslima** [comment]
@Turini can we merge it?

**Comment by Turini** [comment]
:ok_hand:

**Comment by Turini** [comment]
thanx @nykolaslima

**Comment by nykolaslima** [comment]
:tada:

**Pull request merged**
