### PR TITLE
Handling ValidationExceptions in interceptors

### PR DESCRIPTION
**Pull request by csokol**
Please do not merge it yet, it's a work in progress related with #858 

My idea here is to extract classes to better deal with exception handling so then we could reuse the exception handling code to develop that  `@ValidationInterceptor` feature that @lucascs proposed.

I've implemented a `Try` class, similar to the scala's Try monad. Is not a proper monad here, but I think it's a nice abstraction to handle exceptions, what do you think? @lucascs @Turini @garcia-jj

### CODE REVIEW

**Comment by nykolaslima** [comment]
@Turini can we make a relase with it? The `ValidationException` thrown from an interceptor is fixed by this PR but the last VRaptor release (4.2.0-RC3) doesn't have this fix.

**Comment by Turini** [comment]
hey @nykolaslima.

sure, I'm planning to do that tomorrow during the morning. Will let u know

**Comment by Turini** [comment]
done!

**Comment by filipesg** [comment]
Is this available on 4.2.0-RC5? I'm getting error 500 on this code:
`validator.onErrorForwardTo("/url");`
It's inside an interceptor. I need to use any kind of extra annotation to catch this validation error?

**Pull request merged**
