### PR TITLE
Improving explanations

### PR DESCRIPTION
**Pull request by cassunde**
improving somewhat the explanations about controller rest

### CODE REVIEW

**Comment by Turini** [comment]
thanks for this pull-request, Mattheus.

I’ll read carefully until the weekend, and reach you back (:

**Comment by cassunde** [comment]
OK, i keep waiting... It's my first contribution. ;)

**Comment by Turini** [comment]
merged! congrats on your first contribution (;

**Comment by cassunde** [comment]
Thank you,  let's create some guides? very objectives and simple

**Comment by Turini** [comment]
sure! any contribution will be very welcome

**Pull request merged**
